* What is this?

This is my emacs config. I'm trying out this [[http://orgmode.org/worg/org-contrib/babel/intro.html][org-babel]] thing. Basically my init
file is one huge org file with blocks of elisp code sprinkled throughout. Those
blocks are evaluated by org-babel on startup.

* How do I view it?

GitHub can read =.org= files and render them nicely, but since the file is so
long, I recommend viewing it in org-mode where things are collapsible.

* Why =org-babel=?

*Benefits*:

- *all* settings in one file
- everything is hierarchically organized
- (mostly) everything is explained
- org-mode features are available
- it's fun

* License

*The MIT License (MIT)*

Copyright (c) 2016 Austin W. Smith

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
